Repository sainik-khaddar/Hunt-SuperHeroes, pull requests merged in 2022-10, with the labels that each got.

#1 Update home.css
  assets/css/home.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, nice-fix

#2 Corrected Header
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#3 Update readme.md
  readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#5 FORMATED PROJECT
  readme.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#6 Update index.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted
